import os
import polib

translations = {
    "en": {
        "You have successfully registered! Please log in.": "You have successfully registered! Please log in.",
        "Username or email already exists!": "Username or email already exists!",
        "Error loading country list: {}": "Error loading country list: {}",
        "Country list file not found": "Country list file not found",
        "You were successfully logged in!": "You were successfully logged in!",
        "Login failed. Check your credentials and try again.": "Login failed. Check your credentials and try again.",
        "Please select a city first.": "Please select a city first.",
        "You have been logged out.": "You have been logged out.",
        "Your profile has been updated!": "Your profile has been updated!",
        "Your account has been deleted successfully.": "Your account has been deleted successfully.",
        "Please select a valid city.": "Please select a valid city.",
        "Rate by the users: {:.2f}": "Rate by the users: {:.2f}",
        "{} has not been rated yet.": "{} has not been rated yet.",
        "You should visit {}": "You should visit {}",
        "No points available for the selected category: {}.": "No points available for the selected category: {}.",
        "Category '{}' does not exist in the selected city.": "Category '{}' does not exist in the selected city.",
        "Thank you! The new average rating for {} in {} is {:.2f}.": "Thank you! The new average rating for {} in {} is {:.2f}.",
        "Rating must be between 1 and 5.": "Rating must be between 1 and 5.",
        "Please enter a valid number for rating.": "Please enter a valid number for rating.",
        "The place \"{}\" does not exist in {} under the category \"{}\".": "The place \"{}\" does not exist in {} under the category \"{}\".",
        "The point \"{}\" already exists in {}.": "The point \"{}\" already exists in {}.",
        "Place added successfully in {}!": "Place added successfully in {}!",
        "{} added successfully in {}!": "{} added successfully in {}!",
        "The point \"{}\" was successfully deleted from {}.": "The point \"{}\" was successfully deleted from {}.",
        "You do not have permission to delete the point \"{}\".": "You do not have permission to delete the point \"{}\".",
        "Add a New Point": "Add a New Point",
        "Name the new point:": "Name the new point:",
        "Category:": "Category:",
        "Latitude:": "Latitude:",
        "Longitude:": "Longitude:",
        "Add Point": "Add Point",
        "Choose a Category": "Choose a Category",
        "Please, choose between Architecture, Art or Urban spaces:": "Please, choose between Architecture, Art or Urban spaces:",
        "Architecture": "Architecture",
        "Art": "Art",
        "Urban Spaces": "Urban Spaces",
        "Welcome to": "Welcome to",
        "Find a point": "Find a point",
        "Rate a Point": "Rate a Point",
        "Add a Point": "Add a Point",
        "Delete a Point": "Delete a Point",
        "Are you sure you want to delete your account? This action cannot be undone.": "Are you sure you want to delete your account? This action cannot be undone.",
        "Delete my Account": "Delete my Account",
        "Point to Delete:": "Point to Delete:",
        "Delete Point": "Delete Point",
        "Username": "Username",
        "Birth Year": "Birth Year",
        "Country": "Country",
        "Email": "Email",
        "New Password": "New Password",
        "Leave blank to keep your current password.": "Leave blank to keep your current password.",
        "Save Changes": "Save Changes",
        "Place Name": "Place Name",
        "Rating (1-5):": "Rating (1-5):",
        "Go back to your user page": "Go back to your user page",
        "Go back to the main page": "Go back to the main page",
        "Go!":"Go!",
        "Choose a Category": "Choose a Category",
        "Hi": "Hi",
        "! Let's choose a city": "! Let's choose a city",
        "Welcome to ": "Welcome to ",
        "Let's Log in": "Let's Log in",
        "Let's sign up": "Let's sign up",
        "Welcome to {}!": "Welcome to {}!"

    },
    "es": {
        "You have successfully registered! Please log in.": "Te has registrado con éxito. ¡Por favor, inicia sesión!",
        "Username or email already exists!": "¡El nombre de usuario o correo electrónico ya existe!",
        "Error loading country list: {}": "Error al cargar la lista de países: {}",
        "Country list file not found": "No se encontró el archivo de la lista de países",
        "You were successfully logged in!": "¡Has iniciado sesión con éxito!",
        "Login failed. Check your credentials and try again.": "Error en el inicio de sesión. Verifica tus credenciales e inténtalo de nuevo.",
        "Please select a city first.": "Por favor, selecciona una ciudad primero.",
        "You have been logged out.": "Has cerrado sesión.",
        "Your profile has been updated!": "¡Tu perfil ha sido actualizado!",
        "Your account has been deleted successfully.": "Tu cuenta ha sido eliminada con éxito.",
        "Please select a valid city.": "Por favor, selecciona una ciudad válida.",
        "Rate by the users: {:.2f}": "Calificación por los usuarios: {:.2f}",
        "{} has not been rated yet.": "{} aún no ha sido calificado.",
        "You should visit {}": "Deberías visitar {}",
        "No points available for the selected category: {}.": "No hay puntos disponibles para la categoría seleccionada: {}.",
        "Category '{}' does not exist in the selected city.": "La categoría '{}' no existe en la ciudad seleccionada.",
        "Thank you! The new average rating for {} in {} is {:.2f}.": "¡Gracias! La nueva calificación promedio para {} en {} es {:.2f}.",
        "Rating must be between 1 and 5.": "La calificación debe estar entre 1 y 5.",
        "Please enter a valid number for rating.": "Por favor, introduce un número válido para calificar.",
        "The place \"{}\" does not exist in {} under the category \"{}\".": "El lugar \"{}\" no existe en {} bajo la categoría \"{}\".",
        "The point \"{}\" already exists in {}.": "El punto \"{}\" ya existe en {}.",
        "Place added successfully in {}!": "¡Lugar añadido con éxito en {}!",
        "{} added successfully in {}!": "¡{} añadido con éxito en {}!",
        "The point \"{}\" was successfully deleted from {}.": "El punto \"{}\" ha sido eliminado con éxito de {}.",
        "You do not have permission to delete the point \"{}\".": "No tienes permiso para eliminar el punto \"{}\".",
        "Add a New Point": "Añadir un Nuevo Lugar",
        "Name the new point:": "Nombre del nuevo lugar:",
        "Category:": "Categoría:",
        "Latitude:": "Latitud:",
        "Longitude:": "Longitud:",
        "Add Point": "Añadir Lugar",
        "Choose a Category": "Elige una Categoría",
        "Please, choose between Architecture, Art or Urban spaces:": "Por favor, elige entre Arquitectura, Arte o Espacios Urbanos:",
        "Architecture": "Arquitectura",
        "Art": "Arte",
        "Urban Spaces": "Espacios Urbanos",
        "Welcome to": "Bienvenido a",
        "Find a point": "Encuentra un lugar",
        "Rate a Point": "Valora un Lugar",
        "Add a Point": "Añadir un Lugar",
        "Delete a Point": "Eliminar un Lugar",
        "Are you sure you want to delete your account? This action cannot be undone.": "¿Estás seguro de que deseas eliminar tu cuenta? Esta acción no se puede deshacer.",
        "Delete my Account": "Eliminar mi Cuenta",
        "Point to Delete:": "Lugar a Eliminar:",
        "Delete Point": "Eliminar Lugar",
        "Username": "Nombre de Usuario",
        "Birth Year": "Año de Nacimiento",
        "Country": "País",
        "Email": "Correo Electrónico",
        "New Password": "Nueva Contraseña",
        "Leave blank to keep your current password.": "Deja en blanco para mantener tu contraseña actual.",
        "Save Changes": "Guardar Cambios",
        "Place Name": "Nombre del Lugar",
        "Rating (1-5):": "Calificación (1-5):",
        "Go back to your user page": "Volver a tu página de usuario",
        "Go back to the main page": "Volver a la página principal",
        "Go!":"Ir!",
        "Choose a Category": "Elige una Categoría",
        "Hi": "Hola",
        "! Let's choose a city": "¡Vamos a elegir una ciudad!",
        "Welcome to ": "Bienvenido a ",
        "Let's Log in": "Iniciemos Sesión",
        "Let's sign up": "Regístrate",
        "Welcome to {}!": "Bienvenido a {}!"
    },
    "ca": {
        "You have successfully registered! Please log in.": "T'has registrat amb èxit. Si us plau, inicia sessió!",
        "Username or email already exists!": "El nom d'usuari o el correu electrònic ja existeix!",
        "Error loading country list: {}": "Error en carregar la llista de països: {}",
        "Country list file not found": "No s'ha trobat el fitxer de la llista de països",
        "You were successfully logged in!": "Has iniciat sessió amb èxit!",
        "Login failed. Check your credentials and try again.": "Error en iniciar sessió. Verifica les teves credencials i torna a intentar-ho.",
        "Please select a city first.": "Si us plau, selecciona una ciutat primer.",
        "You have been logged out.": "Has tancat sessió.",
        "Your profile has been updated!": "El teu perfil s'ha actualitzat!",
        "Your account has been deleted successfully.": "El teu compte s'ha eliminat amb èxit.",
        "Please select a valid city.": "Si us plau, selecciona una ciutat vàlida.",
        "Rate by the users: {:.2f}": "Puntuació pels usuaris: {:.2f}",
        "{} has not been rated yet.": "{} encara no ha estat puntuat.",
        "You should visit {}": "Hauries de visitar {}",
        "No points available for the selected category: {}.": "No hi ha punts disponibles per a la categoria seleccionada: {}.",
        "Category '{}' does not exist in the selected city.": "La categoria '{}' no existeix a la ciutat seleccionada.",
        "Thank you! The new average rating for {} in {} is {:.2f}.": "Gràcies! La nova puntuació mitjana per a {} a {} és {:.2f}.",
        "Rating must be between 1 and 5.": "La puntuació ha d'estar entre 1 i 5.",
        "Please enter a valid number for rating.": "Si us plau, introdueix un número vàlid per puntuar.",
        "The place \"{}\" does not exist in {} under the category \"{}\".": "El lloc \"{}\" no existeix a {} sota la categoria \"{}\".",
        "The point \"{}\" already exists in {}.": "El punt \"{}\" ja existeix a {}.",
        "Place added successfully in {}!": "Lloc afegit amb èxit a {}!",
        "{} added successfully in {}!": "{} afegit amb èxit a {}!",
        "The point \"{}\" was successfully deleted from {}.": "El punt \"{}\" ha estat eliminat amb èxit de {}.",
        "You do not have permission to delete the point \"{}\".": "No tens permís per eliminar el punt \"{}\".",
        "Add a New Point": "Afegeix un Nou Punt",
        "Name the new point:": "Nom del nou punt:",
        "Category:": "Categoria:",
        "Latitude:": "Latitud:",
        "Longitude:": "Longitud:",
        "Add Point": "Afegeix Punt",
        "Choose a Category": "Tria una Categoria",
        "Please, choose between Architecture, Art or Urban spaces:": "Si us plau, tria entre Arquitectura, Art o Espais Urbans:",
        "Architecture": "Arquitectura",
        "Art": "Art",
        "Urban Spaces": "Espais Urbans",
        "Welcome to": "Benvingut a",
        "Find a point": "Troba un punt",
        "Rate a Point": "Valora un Punt",
        "Add a Point": "Afegeix un Punt",
        "Delete a Point": "Elimina un Punt",
        "Are you sure you want to delete your account? This action cannot be undone.": "Estàs segur que vols eliminar el teu compte? Aquesta acció no es pot desfer.",
        "Delete my Account": "Elimina el meu Compte",
        "Point to Delete:": "Punt a Eliminar:",
        "Delete Point": "Elimina Punt",
        "Username": "Nom d'Usuari",
        "Birth Year": "Any de Naixement",
        "Country": "País",
        "Email": "Correu Electrònic",
        "New Password": "Nova Contrasenya",
        "Leave blank to keep your current password.": "Deixa en blanc per mantenir la teva contrasenya actual.",
        "Save Changes": "Desa els Canvis",
        "Place Name": "Nom del Lloc",
        "Rating (1-5):": "Puntuació (1-5):",
        "Go back to your user page": "Torna a la teva pàgina d'usuari",
        "Go back to the main page": "Torna a la pàgina principal",
        "Go!": "Anar!",
        "Choose a Category": "Tria una Categoria",
        "Hi": "Hola",
        "! Let's choose a city": "Triem una ciutat!",
        "Welcome to ": "Benvingut a ",
        "Let's Log in": "Iniciem Sessió",
        "Let's sign up": "Registra't",
        "Welcome to {}!": "Benvingut a {}!"
    }
}

def generate_po_files(translations, output_dir):
    for lang_code, messages in translations.items():
        po = polib.POFile()
        po.metadata = {
            'Project-Id-Version': 'PROJECT VERSION',
            'Report-Msgid-Bugs-To': 'EMAIL@ADDRESS',
            'POT-Creation-Date': '2024-08-29 23:46+0200',
            'PO-Revision-Date': 'YEAR-MO-DA HO:MI+ZONE',
            'Last-Translator': 'FULL NAME <EMAIL@ADDRESS>',
            'Language': lang_code,
            'Language-Team': f'{lang_code} <LL@li.org>',
            'Plural-Forms': 'nplurals=2; plural=(n != 1);',
            'MIME-Version': '1.0',
            'Content-Type': 'text/plain; charset=utf-8',
            'Content-Transfer-Encoding': '8bit',
            'Generated-By': 'Babel 2.16.0'
        }

        for msgid, msgstr in messages.items():
            entry = polib.POEntry(msgid=msgid, msgstr=msgstr)
            po.append(entry)

        output_file = os.path.join(output_dir, f'messages_{lang_code}.po')
        po.save(output_file)

# Specify the output directory
output_dir = 'translations/'

# Generate the .po files
generate_po_files(translations, output_dir)
